//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDTraderSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveMission
    {
        public int MissionID { get; set; }
        public string MissionType { get; set; }
        public string DestinationSystem { get; set; }
        public string DestinationStation { get; set; }
        public Nullable<int> Expiry { get; set; }
    }
}
