//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDTraderSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargoHold
    {
        public int TradeID { get; set; }
        public string CommodityName { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<float> AvgPurchasePrice { get; set; }
        public Nullable<bool> Stolen { get; set; }
        public Nullable<bool> StockChecked { get; set; }
        public Nullable<bool> MissionCargo { get; set; }
    }
}
