//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDTraderSQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDTSQLEntities : DbContext
    {
        public EDTSQLEntities()
            : base("name=EDTSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveMission> ActiveMissions { get; set; }
        public virtual DbSet<CargoHold> CargoHolds { get; set; }
        public virtual DbSet<Commodity> Commodities { get; set; }
        public virtual DbSet<CommodityGroup> CommodityGroups { get; set; }
        public virtual DbSet<Faction> Factions { get; set; }
        public virtual DbSet<MarketDetail> MarketDetails { get; set; }
        public virtual DbSet<MaterialList> MaterialLists { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<RareCommodity> RareCommodities { get; set; }
        public virtual DbSet<StarSystem> StarSystems { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
    }
}
