//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDTraderSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faction
    {
        public int FactionID { get; set; }
        public string SSIDFaction { get; set; }
        public Nullable<int> StarSystemID { get; set; }
        public string FactionName { get; set; }
    
        public virtual StarSystem StarSystem { get; set; }
    }
}
