//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDTraderSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StarSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StarSystem()
        {
            this.Factions = new HashSet<Faction>();
            this.MarketDetails = new HashSet<MarketDetail>();
            this.Stations = new HashSet<Station>();
        }
    
        public int SystemID { get; set; }
        public string SystemName { get; set; }
        public float SpaceX { get; set; }
        public float SpaceY { get; set; }
        public float SpaceZ { get; set; }
        public string Government { get; set; }
        public string Allegiance { get; set; }
        public string Economy { get; set; }
        public string SystemFaction { get; set; }
        public Nullable<int> TimesVisited { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faction> Factions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarketDetail> MarketDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Station> Stations { get; set; }
    }
}
